name: staphscope
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - biopython>=1.79
  - pandas>=1.3.0
  - blast  # Only BLAST is needed externally
  - pip
  - pip:
    - staphscope
