name: staphscope-env
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python
  - pandas
  - biopython
  - psutil
  - request
  - tqdm
  - click
  - abricate=1.0.1
  - perl
  - any2fasta
  - blast
  - pip
  # Perl dependencies for abricate
  - perl-moo
  - perl-list-moreutils
  - perl-json
  - perl-lwp-protocol-https
  - perl-path-tiny
  - perl-data-dumper
  - perl-getopt-long
  - perl-file-which
