name: staphscope
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - biopython>=1.79
  - pandas>=1.3.0
  - mlst
  - spatyper
  - blast
  - pip
  - pip:
    - staphscope-typing-tool
