{% set name = "staphscope" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/staphscope-{{ version }}.tar.gz
  sha256: # You'll need to calculate this after building the package

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - staphscope = staphscope.cli:main

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - biopython >=1.79
    - pandas >=1.3.0
    - blast  # Only BLAST is needed externally

test:
  commands:
    - staphscope --help
  imports:
    - staphscope

about:
  home: https://github.com/bbeckley-hub/staphscope-typing-tool
  license: MIT
  license_file: LICENSE
  summary: 'Staphscope Typing Tool — MLST + spa + SCCmec typing for Staphylococcus aureus'
  description: |
    A unified MLST + spa + SCCmec typing tool for Staphylococcus aureus.
  doc_url: https://github.com/bbeckley-hub/staphscope-typing-tool
  dev_url: https://github.com/bbeckley-hub/staphscope-typing-tool
